// See https://slint-ui.com/releases/0.2.1/docs/rust/slint/docs/builtin_elements/index.html
// See https://slint-ui.com/releases/0.2.0/docs/rust/slint/docs/widgets/index.html
// See https://docs.rs/slint/latest/slint/docs/langref/index.html

//import { Button, VerticalBox, HorizontalBox} from "std-widgets.slint";

import {SelectScreen} from "./selectscreen.slint";
import {MoreSelectScreen} from "./moreselectscreen.slint";
import {BluetoothScreen, Bluetooth} from "./bluetoothscreen.slint";
import {ActiveScreen, Screens, Source} from "./common.slint";

// re-export for the native code
export { Bluetooth }
export { Source }


// TODO different pages - See https://slint-ui.com/releases/0.2.1/editor/?load_url=https://raw.githubusercontent.com/slint-ui/slint/master/examples/printerdemo/ui/printerdemo.slint

export AppWindow := Window { 
    property <string> thing : "This is a thing" ;
    title: "Modular Audio";
    
    // 5" display
    width: 800px;
    height: 480px;

    // width: 480px;
    // height: 320px;

    // 7" display
    // width: 1024px;
    // height: 600px;

    background: black;
    //callback select-source();
    callback select-screen();

    SelectScreen {
        visible : ActiveScreen.id == Screens.select-source;  
        opacity: ActiveScreen.id == Screens.select-source ? 1. : 0.;
        animate opacity {  duration: 500ms;}
    }

    MoreSelectScreen {
        visible: ActiveScreen.id == Screens.more-select-source ;
        opacity: ActiveScreen.id == Screens.more-select-source ? 1. : 0.;
        animate opacity {  duration: 500ms;}
    }

    BluetoothScreen {  
        visible: ActiveScreen.id == Screens.bluetooth ;
        opacity: ActiveScreen.id == Screens.bluetooth ? 1. : 0.;
        animate opacity {  duration: 500ms;}
    } 

    

}
    
