// See https://slint-ui.com/releases/0.2.1/docs/rust/slint/docs/builtin_elements/index.html
// See https://slint-ui.com/releases/0.2.0/docs/rust/slint/docs/widgets/index.html
// See https://docs.rs/slint/latest/slint/docs/langref/index.html

//import { Button, VerticalBox, HorizontalBox} from "std-widgets.slint";

import {SelectScreen} from "./selectscreen.slint";

// TODO different pages - See https://slint-ui.com/releases/0.2.1/editor/?load_url=https://raw.githubusercontent.com/slint-ui/slint/master/examples/printerdemo/ui/printerdemo.slint

export AppWindow := Window { 
    title: "Modular Audio";
    width: 800px;
    height: 480px;
    background: black;
    callback select_source();
    
    SelectScreen {}
    
    
    
}
