import { SelectButton, Logo, Screens, Palette} from "./common.slint";

export global Bluetooth := {
    property <bool> connecting : false;
  
}

export  BluetoothScreen := HorizontalLayout {
        
    padding: 5px;
    VerticalLayout {
        spacing:10px;
        SelectButton { text: "Previous"; image: @image-url("../images/skip_previous_black_24dp.svg"); }
        SelectButton { }
        SelectButton { }
        SelectButton { }
    }
    
    VerticalLayout { 
        //Logo {height : 30px;}
        // Text {
        //     text: "Sources";
        //     color: white;
        //     font-size: 16px;
        //     horizontal-alignment: TextHorizontalAlignment.center;
        //     vertical-alignment: TextVerticalAlignment.center;
        // }
        Rectangle {  
            GridLayout { 
                Row {
                    Rectangle {  }
                    Rectangle {  }
                    Rectangle {  }
                }
                Row {
                    Rectangle {  }
                    Image {
                        source: @image-url("../images/bluetooth_audio_black_24dp.svg");
                        colorize: Bluetooth.connecting ? orange : Palette.highlight-color;
                        width: source.width * 4 * 1px;
                    }
                    Rectangle {  }
                }
                Row {
                    Rectangle {  }
                    Rectangle {  }
                    Rectangle {  }
                }
                
            }
        }
        
    }
    
    
    
    VerticalLayout {
        spacing: 10px;
        //padding: 5px;
        SelectButton { text: "Next"; image: @image-url("../images/skip_next_black_24dp.svg"); reversed-order: true;}
        SelectButton {}
        SelectButton { }
        SelectButton { text: "Back"; image:@image-url("../images/keyboard_return_black_24dp.svg"); reversed-order: true; }
        // Following go into the "More ..." screen
        //SelectButton { text: "TOSLINK"; reversed-order: true;}
        //SelectButton { text: "Aux In"; reversed-order: true;}
    }

    
}