import { SelectButton, Logo } from "./common.slint";

export SelectScreen := HorizontalLayout {
        
    padding: 5px;
    VerticalLayout {
        spacing:10px;
        SelectButton { text: "Bluetooth"; image: @image-url("../images/bluetooth_black_24dp.svg");}
        SelectButton { text: "Airplay"; image: @image-url("../images/cast_black_24dp.svg"); }
        SelectButton { text: "Internet Radio"; image: @image-url("../images/radio_black_24dp.svg"); }
        SelectButton { text: "DAB Radio"; image: @image-url("../images/radio_black_24dp.svg"); }
    }
    
    VerticalLayout { 
        Logo {height : 30px;}
        Text {
            text: "Sources";
            color: white;
            font-size: 16px;
            horizontal-alignment: TextHorizontalAlignment.center;
            vertical-alignment: TextVerticalAlignment.center;
        }
    }
    
    
    
    VerticalLayout {
        spacing: 10px;
        //padding: 5px;
        SelectButton { text: "CD"; image: @image-url("../images/album_black_24dp.svg"); reversed-order: true;}
        SelectButton { text: "DVD"; image:@image-url("../images/album_black_24dp.svg"); reversed-order: true;}
        SelectButton { text: "More"; image:@image-url("../images/more_horiz_black_24dp.svg"); reversed-order: true; next-screen-id: 1;}
        SelectButton { text: "Settings"; image:@image-url("../images/settings_black_24dp.svg"); reversed-order: true;}
        // Following go into the "More ..." screen
        //SelectButton { text: "TOSLINK"; reversed-order: true;}
        //SelectButton { text: "Aux In"; reversed-order: true;}
    }

    
}