import { SelectButton, Logo, Screens, SelectButtons} from "./common.slint";

export SelectScreen := HorizontalLayout {
    
    padding: 5px;
    VerticalLayout {
        spacing:10px;
        SelectButton { text: "Bluetooth"; image: @image-url("../images/bluetooth_black_24dp.svg"); id: SelectButtons.bluetooth; next-screen-id: Screens.bluetooth;}
        SelectButton { text: "Airplay"; image: @image-url("../images/cast_black_24dp.svg"); id: SelectButtons.airplay;}
        SelectButton { text: "Internet Radio"; image: @image-url("../images/radio_black_24dp.svg"); id: SelectButtons.internet-radio; }
        SelectButton { text: "DAB Radio"; image: @image-url("../images/radio_black_24dp.svg"); id: SelectButtons.dab-radio;}
    }
    
    VerticalLayout { 
        Logo {height : 30px;}
        Text {
            text: "Sources";
            color: white;
            font-size: 16px;
            horizontal-alignment: TextHorizontalAlignment.center;
            vertical-alignment: TextVerticalAlignment.center;
        }
    }
    
    
    
    VerticalLayout {
        spacing: 10px;
        //padding: 5px;
        SelectButton { text: "CD"; image: @image-url("../images/album_black_24dp.svg"); reversed-order: true;id: SelectButtons.cd;}
        SelectButton { text: "DVD"; image:@image-url("../images/album_black_24dp.svg"); reversed-order: true;id: SelectButtons.dvd;}
        SelectButton { text: "More"; image:@image-url("../images/more_horiz_black_24dp.svg"); reversed-order: true; next-screen-id: Screens.more-select-source; id: SelectButtons.more-sources;}
        SelectButton { text: "Settings"; image:@image-url("../images/settings_black_24dp.svg"); reversed-order: true; id: SelectButtons.settings;}
        // Following go into the "More ..." screen
        //SelectButton { text: "TOSLINK"; reversed-order: true;}
        //SelectButton { text: "Aux In"; reversed-order: true;}
    }

    
}