@startuml Settings
skinparam actorStyle awesome
left to right direction

actor "Amplifer User" as user

rectangle Amplifier-Module {
     
    user --> Settings

    package Settings {
        usecase (Display WLAN) as disp_wlan
        usecase (Edit WLAN) as edit_wlan
        usecase (Edit WLAN SSID) as wlan_ssid
        usecase (Edit WLAN Password) as wlan_pass

        edit_wlan ..> disp_wlan : << includes >>
        edit_wlan ..> wlan_ssid : << includes >>  
        edit_wlan ..> wlan_pass : << includes >>
        
        usecase (Keyboard Entry) as keyboard

        keyboard ..> KeyboardEntry

        wlan_ssid ..> keyboard : << includes >>
        wlan_pass ..> keyboard : << includes >>
        
    }

    

    package KeyboardEntry  {
        usecase (Keyboard \n Left) as left
        usecase (Keyboard \n Right) as right
        usecase (Keyboard \n Up) as up
        usecase (Keyboard \n Down) as down
        usecase (Keyboard \n Enter) as enter

    }


}



@enduml
